"""DB create

Revision ID: 0013474ae6af
Revises: 
Create Date: 2023-11-15 18:49:12.070945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0013474ae6af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_id', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_storageQuantities_id', table_name='storageQuantities')
    op.drop_table('storageQuantities')
    op.drop_index('ix_storages_id', table_name='storages')
    op.drop_table('storages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storages',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('storages_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='storages_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_storages_id', 'storages', ['id'], unique=False)
    op.create_table('storageQuantities',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"storageQuantities_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('storage_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='storageQuantities_product_id_fkey'),
    sa.ForeignKeyConstraint(['storage_id'], ['storages.id'], name='storageQuantities_storage_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='storageQuantities_pkey')
    )
    op.create_index('ix_storageQuantities_id', 'storageQuantities', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    # ### end Alembic commands ###
